---
provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: inspec-gcp
      backend: gcp

platforms:
  - name: terraform

suites:
  - name: simple-project
    driver:
      name: terraform
      root_module_directory: examples/simple-project
      parallelism: 4
      command_timeout: 1800
