name: kitchen-tests

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:  
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: BrownUniversity/terraform-gcp-project

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.save_var.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - id: save_tag
        run: echo "::set-output name=tag::${{ steps.meta.outputs.tags[0] }}"

      - id: print tag
        run: echo "${{ steps.meta.outputs.tags[0] }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  kitchen-tests:
    needs: docker
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/brownuniversity/terraform-gcp-project:${{ needs.docker.outputs.tag }}

    steps:
    - uses: actions/checkout@v1
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test
      env:
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
