name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: brownccv/kitchen-terraform

    env:
      TF_VAR_billing_account: ${{ SECRETS.GCP_BILLING_ACCOUNT }}
      TF_VAR_org_id: ${{ SECRETS.GCP_ORG_ID }}
      TF_VAR_folder_id: ${{ SECRETS.GCP_FOLDER_ID }}

    steps:
    - uses: actions/checkout@v1
    - name: Create Credential File
      run: echo ${{ secrets.GCP_CREDENTIAL_JSON }} > credentials.json
    - name: Run Kitchen
      run: bundle exec kitchen test
      env:
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
